fixes #4 - Added function to access search result aggregation
loklak/loklak_nodejs_api pull request #5
Opened 2017-04-17 17:41 UTC by djmgit

fixed issue #4.Added function to access search result aggregation
API service.

2017-04-18 13:20 UTC, sudheesh001 requested changes
Looks good but a few minor changes.

2017-04-18 13:20 UTC, sudheesh001 commented on lib/loklak.js
> +	console.log(apiUrl);
You can remove this console statement

2017-04-18 13:20 UTC, sudheesh001 commented on lib/loklak.js
>  module.exports = new Loklak();
Please add a new line after the EOF

2017-04-18 13:27 UTC, djmgit commented on lib/loklak.js
> +	console.log(apiUrl);
yeah sure!! I missed it !

2017-04-18 13:37 UTC, djmgit commented
Removed console statement and added EOF line

2017-04-19 04:42 UTC, sudheesh001 approved these changes
Looks good!

2017-04-19 04:42 UTC, merged